name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: CMake set-up
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: make mpeg_ts_unit_tests
    - name: Unit tests
      run: ./mpeg_ts_unit_tests 
