name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get the ts test file
      run: wget https://github.com/andersc/assets/raw/master/bars.ts
    - name: build and run
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release --target mpeg_ts_unit_tests
        ./mpeg_ts_unit_tests 
